title: tree

author: 月伴飞鱼

menus: 
  关于: /about

links:
  github: https://github.com/
  
favicon: /头像.jpg

# valine 
valine:
    # 评论
    enableComment: false 
    # 阅读量
    enableCounter: false
    # valine appID
    appID: QLuwMMF7dvcWXkpd6Udvhb9h-gzGzoHsz
    # valine appKey
    appKey: n6nrOOuITdpIOEIRBK3QQ33O
    placeholder: 请输入评论
    avatar: retro

# 是否开启“不蒜子”来统计访问量
busuanzi: true

# 底部版权开始年份
siteStartYear: 2019

# 图片放大功能
fancybox: true

password: true